apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: governor-tf
  name: governor-tf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: governor-tf
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: governor-tf
    spec:
      containers:
      - args:
        - --rest_api_port=8500
        - --model_name=governor.tf
        - --model_base_path=/mnt/export
        command:
        - /usr/bin/tensorflow_model_server
        image: tens/governor-tf
        imagePullPolicy: IfNotPresent
        name: governor-tf
        ports:
        - containerPort: 8500
          protocol: TCP
        resources:
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 1Gi
        securityContext:
          procMount: Default
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: governor-tf
  name: governor-tf
spec:
  ports:
  - name: restapi-tf-serving
    port: 8500
    protocol: TCP
    targetPort: 8500
  selector:
    app: governor-tf
  sessionAffinity: None
  type: ClusterIP
